apiVersion: 1

datasources:
  - name: Tesla InfluxDB
    uid: tesla-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: tesla
      defaultBucket: vehicle
    secureJsonData:
      token: ${INFLUX_TOKEN}